remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

location:
  name: China
  url: https://www.google.com/maps/place/China
